version: '2.2'

services:
  tesselserver:
    build:
      context: ../app
      dockerfile: Dockerfile
    image: tesselserver
    ports:
      - "80:80"
    networks:
      - rentman
networks:
  rentman:
    name: rentman