version: '2.2'

services:
  tesselserver:
    build:
      context: ../
      dockerfile: app/Dockerfile
    image: tesselserver
    ports:
      - "80:80"
    networks:
      - rentman
    volumes:
      - ../app:/usr/src/app
networks:
  rentman:
    name: rentman